server:
  port: 8090
spring:
  application:
    name: alibaba-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 98ace971-48b9-40f0-be64-05fb6ceec157
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: alibaba-consumer
          uri: lb://alibaba-consumer
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1